export const FETCH_APP_SUCCESS = 'FETCH_APP_SUCCESS';
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const FETCH_APP_ERROR = 'FETCH_APP_ERROR';
export const FETCH_REPORT_ERROR = 'FETCH_REPORT_ERROR';
